#!/bin/sh
# Copyright (C) 1999-2003 by Salvador E. Tropea (SET),
# see copyrigh file for details
#
echo
echo This batch file configures the packages using the settings that the
echo *maintainer* uses for it\'s own needs.
echo These settings doesn\'t have to be the same you want.
echo The most common defaults are obtained by just running configure.bat.
echo If you want to reconfigure the package first delete configure.cache.
echo
echo Press the \'ENTER\' key to continue or hit \'CTRL+C\' to cancel.
read idontcare
rm -f configure.cache
rm -f Makefile
# gcc 2.95.4 compiles much faster (3.2x average)
#export CC="gcc-2.95"
#export CXX="g++-2.95"
# gcc 3.3.5 generates faster code (+20% aprox. for K7)
#export CC="gcc-3.3"
#export CXX="g++-3.3"
# Note: Using SSC gcc 3.3.5 compiles in less time (1.37x instead of 3.2x)
# gcc 3.4.4 test
#export CC="gcc-3.4"
#export CXX="g++-3.4"
perl config.pl --cflags=-O2\ -Wall\ -Werror\ -gstabs+3\ -pipe \
               --cxxflags=-O2\ -Wall\ -Werror\ -gstabs+3\ -pipe \
               --with-debug --enable-maintainer-mode --without-static \
               --with-ssc "$@"

