#!/usr/bin/make
#
# Copyright (c) 2003-2004 by Salvador E. Tropea
# Covered by the GPL license.
#
# That's the makefile for MSVC compiler.
#
# This file reuses the Makefile.bcc file but defining FOR_NMAKE variable to
# select Microsoft tools.
#

FOR_NMAKE=1
# Uncomment to generate code with debug information.
#DEBUG=1
!include Makefile.bcc

