# Hmmm.. the cygwin version needs -mno-cygwin here... but isn't
# this generated somewhere else? Disabling temporarily for linux.
RHIDE_GCC=gcc
CC=$(RHIDE_GCC)

libtvfintl.a: intldummy.o
	ar -rv libtvfintl.a intldummy.o
